language: objective-c
osx_image: xcode11.2
xcode_project: projects/LibTest/LibTest.xcodeproj
xcode_scheme: LibTestTests
xcode_destination: platform=iOS Simulator,OS=13.2.2,name=iPhone 8
before_install:
- make clean
- make build
- make test
