language: objective-c
osx_image: xcode11.2
xcode_project: projects/LibTest/LibTest.xcodeproj
xcode_scheme: LibTest
xcode_destination: platform=iOS Simulator,OS=13.2.2,name=iPhone 8
before_install:
- make clean
- make build
- make install
- xcodebuild -project projects/LibTest/LibTest.xcodeproj -list
- make test
